### ISSUE TITLE
Please tag a stable release of ASTRAL

### ISSUE THREAD

**Issue by sjackman** [smirarab/ASTRAL#4]
Thanks. cc @tseemann

**Comment by sjackman** [comment]
Please avoid updating the zip file without also changing the version number. There have been [eight changes](https://github.com/smirarab/ASTRAL/commits/master/Astral.4.7.8.zip) to the zip file, all with the same version number. See [Semantic Versioning](http://semver.org/).

**Comment by sjackman** [comment]
See https://github.com/Homebrew/homebrew-science/pull/2896

**Comment by smirarab** [comment]
Shaun, 

Thanks for adding to homebrew! 

I just tagged a new version as stable. Unfortunately, I have not been following semantic versioning well up to now, and because I have three parallel development branches, it will take me a bit of time to get to good structured semantic versioning. I hope to get there in the next couple of months. 

Multiple changes to the zip file were only on documentation files. But, I do see your point. I will try to avoid that in future. 

Thanks for the pointers!
