### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by grcolli** [smirarab/ASTRAL#74]
**Describe the bug**
Execution interrupted with the following message:
"Segmentation fault (core dumped)"

**To Reproduce**
java -Djava.library.path=/home/grcolli/Astral-MP/lib/ -jar astral.5.15.4.jar -i locus75loci.treefile -o out.tre 2>astral.log 

**Log file**
Send us the log file (standard error of ASTRAL)

** Version
astral.5.15.4.jar
[astral.log](https://github.com/smirarab/ASTRAL/files/6656719/astral.log)

 

**Additional context**

**Comment by smirarab** [comment]
I do not see the error in the log file but perhaps for some reason, it was not caught. Since I am not able to reproduce the error on my side, I will need to ask you for some help. 

I have three suggestions. 

1. Try running `make.sh` on your machine. That may solve the issue. 
2. Let me know what version of java you are running. 
3. Can you see if the error is reproduced if you run on a different input, say the small test files included with the package? 

Thank you.

**Comment by grcolli** [comment]
1. make.sh returns "make.sh: command not found"

2. java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

3. The code runs smoothly on the 1KP-genetrees.tre test file

Still trying to figure out what's happening. Thanks for the advice!

**Comment by smirarab** [comment]
To build, go to ASTRAL directory and try `./make.sh` or `bash make.sh`. 

If the problem is only reproducible with your input file, it would be helpful to send me the file (email it to smirarab@ucsd.edi).

PS: glad to hear 5.7.7 finished. 5.15.4 is a multi-threaded version of the same algorith, so you do not need to run 5.15.4 if 5.7.7 works fine.

**Comment by grcolli** [comment]
I reinstalled ASTRAL-MP and everything is working! The multi-threaded version is a lot faster (on a workstation with 44 cores). Thanks for all your help!
